create table silk_collect
(
    collect_id   int auto_increment comment '数据主键'
        primary key,
    collect_type varchar(20)                 not null comment '收集品类型',
    scene_name   varchar(20)                 not null comment '场景名',
    after_data   text                        not null comment '更新后数据',
    scene_id     varchar(27)                 null comment '场景代码',
    axis_x       int                         null comment 'x坐标',
    axis_y       int                         null comment 'y坐标',
    remark       varchar(90) charset utf8mb3 null comment '备注'
)
    comment '丝之歌收集数据';

insert into silk_collect (collect_id, collect_type, scene_name, after_data, scene_id, axis_x, axis_y, remark)
values  (1, '金属', '骸骨洞窟', '{ "SceneName": "Bone_07", "ID": "Collectable Item Pickup - Tool Metal", "Value": true, "Mutator": 0 }', 'Bone_07', 37, 5, 'Value之前为false'),
        (2, '金属', '深钨', '{ "SceneName": "Dock_03", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0 }', 'Dock_03', null, null, null),
        (3, '盒子', '猎人小径', '{ "SceneName": "Ant_20", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0 }', 'Ant_20', null, null, 'StoryEvents从此:0面具,1丝轴,2丝心,3盒子'),
        (4, '面具', '远野', '{"SceneName": "Bone_East_20", "ID": "Heart Piece", "Value": true, "Mutator": 0}', 'Bone_East_20', null, null, null),
        (5, '面具', '骸底买面具', '"PurchasedBonebottomHeartPiece": true', '\\', null, null, '之前为false'),
        (6, '金属', '骸底买金属', '"PurchasedBonebottomToolMetal": true', '\\', null, null, null),
        (7, '面具', '沙虫道', '{"SceneName": "Crawl_02", "ID": "Heart Piece", "Value": true, "Mutator": 0}', 'Crawl_02', null, null, null),
        (8, '盒子', '朝圣者息所', '"PurchasedPilgrimsRestMemoryLocket": true', '\\', null, null, null),
        (9, '面具', '甲木林', '{"SceneName": "Shellwood_14", "ID": "Heart Piece", "Value": true, "Mutator": 0}', 'Shellwood_14', null, null, null),
        (10, '盒子', '骨髓洞窟', '{"SceneName": "Bone_18", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Bone_18', null, null, null),
        (11, '面具', '洞窟与深钨之间', '{"SceneName": "Dock_08", "ID": "Heart Piece", "Value": true, "Mutator": 0}', 'Dock_08', 54, 20, null),
        (12, '盒子', '骸底提交暴烈燧甲虫任务', '{"Name": "Rock Rollers", "Data": {"HasBeenSeen": true, "IsAccepted": true, "CompletedCount": 3, "IsCompleted": true, "WasEverCompleted": true}}', '\\', null, null, 'IsCompleted、WasEverCompleted之前都为false'),
        (13, '丝轴', '出生点织巢', '{"SceneName": "Weave_11", "ID": "Silk Spool", "Value": true, "Mutator": 0}', 'Weave_11', 15, 24, null),
        (14, '盒子', '钟镇购买盒子', '"PurchasedBelltownMemoryLocket": true', '\\', null, null, null),
        (15, '盒子', '工厂忏悔机旁光源', '{"SceneName": "Under_08", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Under_08', 61, 18, ''),
        (16, '丝轴', '圣煲工厂', '{"SceneName": "Under_10", "ID": "Silk Spool", "Value": true, "Mutator": 0}', 'Under_10', 22, 6, null),
        (17, '丝轴', '圣扉巨门顶部', '{"SceneName": "Song_19_entrance", "ID": "Silk Spool", "Value": true, "Mutator": 0}', 'Song_19_entrance', 22, 94, null),
        (18, '盒子', '圣煲钟道顶部', '{"SceneName": "Bellway_City", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Bellway_City', 68, 26, null),
        (19, '丝轴', '圣煲工厂底部', '{"SceneName": "Library_11b", "ID": "Silk Spool", "Value": true, "Mutator": 0}', 'Library_11b', 22, 7, null),
        (20, '金属', '圣煲工厂', '{"SceneName": "Under_19b", "ID": "Collectable Item Pickup - Tool Metal", "Value": true, "Mutator": 0}', 'Under_19b', 10, 7, null),
        (21, '丝轴', '灰沼顶部', '{"SceneName": "Greymoor_02", "ID": "Silk Spool", "Value": true, "Mutator": 0', 'Greymoor_02', 30, 137, null),
        (22, '丝轴', '白愈厅救谢尔玛', '{"SceneName": "Ward_09", "ID": "ward_junk_pile_break", "Value": true, "Mutator": 0}', '\\', null, null, null),
        (23, '丝轴', '白愈厅电梯下方', '{"SceneName": "Ward_01", "ID": "Silk Spool", "Value": true, "Mutator": 0}', 'Ward_01', 29, 6, null),
        (24, '丝轴', '钟镇买丝轴', '"PurchasedBelltownSpoolSegment": true', '\\', null, null, null),
        (25, '面具', '圣歌盟地买面具', '"MerchantEnclaveShellFragment": true', '\\', null, null, null),
        (26, '面具', '火灵竹林', '{"SceneName": "Wisp_07", "ID": "Heart Piece", "Value": true, "Mutator": 0}', 'Wisp_07', 251, 24, null),
        (27, '金属', '火灵竹林', '{"SceneName": "Wisp_05", "ID": "Collectable Item Pickup - Tool Metal", "Value": true, "Mutator": 0}', 'Wisp_05', 42, 58, null),
        (28, '丝轴', '忆廊', '{"SceneName": "Arborium_09", "ID": "Silk Spool", "Value": true, "Mutator": 0}', 'Arborium_09', 19, 32, null),
        (29, '盒子', '忆廊', '{"SceneName": "Arborium_05", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Arborium_05', 5, 9, null),
        (30, '金属', '腐殖渠', '{"SceneName": "Aqueduct_05", "ID": "Collectable Item Pickup - Tool Metal", "Value": true, "Mutator": 0}', 'Aqueduct_05', 325, 17, null),
        (31, '面具', '远野岩浆挑战', '{"SceneName": "Bone_East_LavaChallenge", "ID": "Heart Piece (1)", "Value": true, "Mutator": 0}', 'Bone_East_LavaChallenge', 21, 278, '"lavaSpittersEmerge"也变为false'),
        (32, '盒子', '腐汁泽左上角', '{"SceneName": "Shadow_20", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Shadow_20', 18, 25, null),
        (33, '盒子', '腐汁泽打沙包', '{"SceneName": "Shadow_27", "ID": "Sack Corpse Pickup", "Value": true, "Mutator": 0}', 'Shadow_27', 192, 10, null),
        (34, '面具', '腐汁泽', '{"SceneName": "Shadow_13", "ID": "Heart Piece", "Value": true, "Mutator": 0}', 'Shadow_13', 308, 63, null),
        (35, '盒子', '中途酒馆', '{"SceneName": "Halfway_01", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Halfway_01', 9, 15, null),
        (36, '丝轴', '蚀阶小偷购买', '"purchasedGrindleSpoolPiece": true', '\\', null, null, null),
        (37, '盒子', '卡拉卡沙川', '{"SceneName": "Coral_23", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Coral_23', 91, 52, null),
        (38, '金属', '蚀阶', '{"SceneName": "Coral_32", "ID": "Collectable Item Pickup - Tool Metal", "Value": true, "Mutator": 0}', 'Coral_32', 78, 9, null),
        (39, '丝轴', '解救14只跳蚤', '"MetCaravanTroupeLeaderJudge": true', '\\', null, null, 'StoryEvents名称：Coral_Judge_Arena'),
        (40, '盒子', '灰沼车站左侧', '{"SceneName": "Greymoor_16", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Greymoor_16', 131, 53, null),
        (41, '面具', '机枢核心左边', '{"SceneName": "Song_09", "ID": "Heart Piece", "Value": true, "Mutator": 0}', 'Song_09', 42, 43, null),
        (42, '面具', '出生点织巢', '{"SceneName": "Weave_05b", "ID": "Heart Piece", "Value": true, "Mutator": 0}', 'Weave_05b', 161, 29, null),
        (43, '面具', '钟镇猎杀兽蝇任务', '{"Name": "Beastfly Hunt", "Data": {"HasBeenSeen": true, "IsAccepted": true, "CompletedCount": 0, "IsCompleted": true, "WasEverCompleted": true}', '\\', null, null, 'IsCompleted\\WasEverCompleted之前为false'),
        (44, '面具', '图书馆玻璃罐', '{"SceneName": "Library_05", "ID": "library_glass_heart_piece", "Value": true, "Mutator": 0}', 'Library_05', 17, 70, null),
        (45, '丝轴', '高庭顶部', '{"SceneName": "Hang_03_top", "ID": "Silk Spool", "Value": true, "Mutator": 0}', 'Hang_03_top', 18, 156, null),
        (46, '金属', '圣歌盟地买金属', '"MerchantEnclaveToolMetal": true', '\\', null, null, null),
        (47, '丝轴', '圣歌盟地买丝轴', '"MerchantEnclaveSpoolPiece": true', '\\', null, null, null),
        (48, '面具', '罪石监狱上右', '{"SceneName": "Slab_17", "ID": "Heart Piece", "Value": true, "Mutator": 0}', 'Slab_17', 19, 68, null),
        (49, '丝轴', '罪石监狱左侧', '{"SceneName": "Peak_01", "ID": "Silk Spool", "Value": true, "Mutator": 0}', 'Peak_01', 86, 192, null),
        (50, '面具', '雪山', '{"SceneName": "Peak_04c", "ID": "Heart Piece", "Value": true, "Mutator": 0}', 'Peak_04c', 68, 8, null),
        (51, '面具', '蚀阶', '{"SceneName": "Peak_04c", "ID": "Heart Piece", "Value": true, "Mutator": 0}', 'Coral_19b', 75, 108, null),
        (52, '丝轴', '深钨', '{"SceneName": "Bone_East_13", "ID": "Silk Spool", "Value": true, "Mutator": 0}', 'Bone_East_13', 41, 24, null),
        (53, '丝轴', '德鲁伊下方', '{"SceneName": "Bone_11b", "ID": "Silk Spool", "Value": true, "Mutator": 0}', 'Bone_11b', 31, 5, null),
        (54, '丝轴', '深钨右侧', '{"SceneName": "Dock_03c", "ID": "Silk Spool", "Value": true, "Mutator": 0}', 'Dock_03c', 128, 55, null),
        (55, '丝轴', '机枢核心右下', '{"SceneName": "Cog_07", "ID": "Silk Spool", "Value": true, "Mutator": 0}', 'Cog_07', 83, 15, null),
        (56, '盒子', '沙虫道左下', '{"SceneName": "Crawl_09", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Crawl_09', 130, 5, null),
        (57, '盒子', '蚀阶', '{"SceneName": "Coral_02", "ID": "Collectable Item Pickup (1)", "Value": true, "Mutator": 0}', 'Coral_02', 202, 45, null),
        (58, '盒子', '图书馆右上', '{"SceneName": "Library_08", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Library_08', 106, 35, null),
        (59, '盒子', '深钨温泉房下方', '{"SceneName": "Dock_13", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Dock_13', 15, 5, null),
        (60, '盒子', '罪石监狱', '{"SceneName": "Slab_Cell_Quiet", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Slab_Cell_Quiet', 43, 32, null),
        (61, '盒子', '第三幕远野右上方', '{"SceneName": "Bone_East_25", "ID": "Collectable Item Pickup", "Value": true, "Mutator": 0}', 'Bone_East_25', 152, 8, null),
        (62, '面具', '第三幕飞毛腿赛跑', '{"Name": "Sprintmaster Race", "Data": {"HasBeenSeen": false, "IsAccepted": true, "CompletedCount": 0, "IsCompleted": true, "WasEverCompleted": true}}', 'Sprintmaster_Cave', 50, 14, null);